version: '3'
services:
  site_back_postgres:
    container_name: site_back_postgres
    image: postgres:14
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DATABASE: denis

    volumes:
      - postgres:/home/denis/programms/nest/site_back/docker-volumes/postgres
    ports:
      - "5432:5432"
    networks:
      - site_back
    restart: unless-stopped 

  site_back_pgadmin:
    container_name: site_back_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: skitlsskitlovich@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/home/denis/programms/nest/site_back/docker-volumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - site_back
    restart: unless-stopped

networks:
  site_back:
    driver: bridge

volumes: 
  postgres:
  pgadmin:
